apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-app-bg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/smit-darji/k8s-argo-bg-cicd.git'
    targetRevision: Master
    path: bluegreen
  destination:
    server: https://kubernetes.default.svc
    namespace: webapps-bg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
