apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-green
  namespace: webapp-bg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: green
  template:
    metadata:
      labels:
        app: webapp
        version: green
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: webapp
        image: smitdarji/k8s:v.g.0
        ports:
        - containerPort: 80
