apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-blue
  namespace: webapp-bg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: blue
  template:
    metadata:
      labels:
        app: webapp
        version: blue
    spec:
      containers:
        - name: webapp
          image: smitdarji/k8s:v.bb.1.1
          ports:
            - containerPort: 80
