apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webapp-bg
  namespace: webapp-bg
  labels:
    app: webapp
    releaseColor: blue   # CI flips between blue/green
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: webapp
  strategy:
    blueGreen:
      activeService: webapp-bg-stable
      previewService: webapp-bg-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 180
  template:
    metadata:
      labels:
        app: webapp     
    spec:
      containers:
        - name: webapp
          image: smitdarji/k8s:webapp_blue_bc49b94   # CI overwrites to webapp_<color>_<shortsha>
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
