apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webapp-bg
  namespace: webapp-bg
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: webapp
  strategy:
    blueGreen:
      activeService: webapp-bg-stable
      previewService: webapp-bg-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 180
  template:
    metadata:
      labels:
        app: webapp
        version: green
    spec:
      containers:
        - name: webapp
          image: smitdarji/k8s:gg_l.65_4b4350f
          ports:
            - containerPort: 80
