apiVersion: v1
kind: Service
metadata:
  name: k8s-app-bg-service
  namespace: webapps-bg
spec:
  selector:
    app: k8s-app
    version: blue     # 🔁 Change to "green" to switch traffic
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
