apiVersion: v1
kind: Service
metadata:
  name: webapp-bg-stable
  namespace: webapp-bg
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-bg-canary
  namespace: webapp-bg
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
